name: Add or Delete User

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address of User'
        required: true
        
      operation:
        type: choice
        description: 'Choose Operation'
        options:
        - create
        - delete
        required: true
        
      platform:
        type: choice
        description: 'Choose Platform'
        options:
        - All
        - coralogix
        - github
        - jira
        - redash
        - jenkins
        - aws
        - appsignal
        required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
          email: ${{github.event.inputs.email}}
          operation: ${{github.event.inputs.operation}}
          platform: ${{github.event.inputs.platform}}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          CORALOGIX_KEY: ${{ secrets.TEAM_API_KEY_CORALOGIX }}
          EMAIL_ADMIN_JIRA: ${{ secrets.EMAIL_ADMIN_JIRA }}
          DOMAIN_NAME_JIRA: ${{ secrets.DOMAIN_NAME_JIRA}}
          API_KEY_JIRA: ${{ secrets.API_KEY_JIRA}}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install redash-api-client
        pip install sendgrid
        pip install boto3 pandas
        
    - name: Install Coralogix CLI tool
      run: |
        curl -O https://coralogix-public.s3-eu-west-1.amazonaws.com/cxctl/latest/cxctl-Linux.gz
        gunzip -N cxctl-*.gz
        chmod +x cxctl
       
    
    - name: Run python script
      run: |
        
        python .github/workflows/all_in_one.py
